site_name: "Helply"
site_description: "A library that simplifies 'help' command creation for application commands in your disnake bot. Automatically parse and access detailed attributes for your commands."
site_url: "https://dlchamp.github.io/helply"
repo_url: "https://github.com/dlchamp/helply"
repo_name: "dlchamp/helply"
site_dir: "site"
copyright: '&copy; Copyright 2023-present, <a href="https://github.com/DLCHAMP">DLCHAMP'
nav:
  - Home:
    - Overview: index.md
    - License: license.md
  - Code Reference: reference/

  - Examples: examples/
  - Author's Site: https://dlchamp.com



theme:
  favicon: assets/favicon.svg
  name: material
  features:
  - navigation.tabs
  - navigation.top
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: black
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: purple
    toggle:
      icon: material/weather-night
      name: Switch to light mode


extra_css:
  - css/material.css
  - css/mkdocstrings.css
  - css/logo.css


markdown_extensions:
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tilde
  - pymdownx.emoji
  - mdx_truly_sane_lists
  - tables
  - def_list
  - admonition
  - attr_list
  - md_in_html



plugins:
  - search
  - autorefs
  - gen-files:
      scripts:
      - docs/gen_raf_nav.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
        handlers:
          python:
            options:
              docstring_style: numpy
              docstring_section_style: list
              docstring_options:
                merge_init_into_class: true


watch:
  - src/helply



extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/dlchamp
